# Generated by Django 3.2.1 on 2021-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=500)),
                ('api_secret_key', models.CharField(max_length=500)),
                ('access_token', models.CharField(max_length=500)),
                ('access_token_secret', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StatusText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TweetMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(upload_to='')),
                ('file2', models.FileField(blank=True, null=True, upload_to='')),
                ('file3', models.FileField(blank=True, null=True, upload_to='')),
                ('file4', models.FileField(blank=True, null=True, upload_to='')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TweetText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
