# Generated by Django 3.2.1 on 2021-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_alter_tweetmedia_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusText',
        ),
        migrations.DeleteModel(
            name='TweetText',
        ),
        migrations.AlterField(
            model_name='tweetmedia',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
