# Generated by Django 3.2.1 on 2021-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20210527_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.CharField(max_length=100)),
            ],
        ),
    ]
