# Generated by Django 3.2.1 on 2021-05-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_searchlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.CharField(max_length=100)),
                ('texts', models.CharField(max_length=500)),
            ],
        ),
    ]
