# Generated by Django 3.2.1 on 2021-05-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_searchretweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchfollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.CharField(max_length=100)),
            ],
        ),
    ]
