# Generated by Django 3.2.1 on 2021-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_searchfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchintraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.CharField(max_length=100)),
                ('text_for_reply', models.CharField(max_length=500)),
            ],
        ),
    ]
